name: Build Release

on:
  release:
    types: [created]

jobs:
  release-linux:
    name: release linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz"
#  release-darwin:
#    name: release darwin (darwin, amd64)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: wangyoucao577/go-release-action@v1.4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          goos: darwin
#          goarch: amd64
#          goversion: "https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz"